
package javaapplication5;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class PesquisaEntrada extends javax.swing.JFrame {
    
    
    String comp; //utilizarei para teste de comparaçao de strings
    String[] palavras; //adicionarei as linhas a  esse vetor
    Boolean result = true; //utilizado caso a busca não retorne nenhum valor
        
    String nome = "D:/Users/Elison/Documents/projeto_pesquisa_ildeu/ARQCAT.PCI";    
    //String nome = "ARQCAT.PCI"; //arquivo de texto que abrirei
    
    
    DefaultTableModel Modelo ;
    
         
    public void LoadTableResultados(){
       
    }    
        
    
    public PesquisaEntrada() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTePesquisa.setEnabled(false);
        
        //System.out.println(Modelo);
        //lendo o arquivo de texto
        try{ 
            FileReader arq = new FileReader(nome);
            BufferedReader lerArq = new BufferedReader(arq);
 
            String linha;
            
            do{
            
            linha= lerArq.readLine(); // lê a primeira linha
            // a variável "linha" recebe o valor "null" quando o processo
            // de repetição atingir o final do arquivo texto
                if(linha != null){

                    palavras = linha.split("Gn"); //separa as linhas apartir dos Gn no arquivo
                    
        }
            }while(linha != null);
        
        arq.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Arquivo " + nome + " não Encontrado!");
            System.exit(0);
           
        }
        //termino da leitur do rquivo e suas excessões
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupNomeTel = new javax.swing.ButtonGroup();
        jLaPesquisa = new javax.swing.JLabel();
        jTePesquisa = new javax.swing.JTextField();
        jBuPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaResultado = new javax.swing.JTable();
        jRaNome = new javax.swing.JRadioButton();
        jRaTelefone = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLaPesquisa.setText("Pesquisa:");

        jBuPesquisar.setText("Pesquisar");
        jBuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuPesquisarActionPerformed(evt);
            }
        });

        jTaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Os", "Nome", "Telefone", "Tipo", "Marca", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTaResultado);
        if (jTaResultado.getColumnModel().getColumnCount() > 0) {
            jTaResultado.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTaResultado.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTaResultado.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTaResultado.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTaResultado.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTaResultado.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        buttonGroupNomeTel.add(jRaNome);
        jRaNome.setText("Nome");
        jRaNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRaNomeMouseClicked(evt);
            }
        });

        buttonGroupNomeTel.add(jRaTelefone);
        jRaTelefone.setText("Telefone");
        jRaTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRaTelefoneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRaNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRaTelefone))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLaPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jTePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jBuPesquisar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRaNome)
                    .addComponent(jRaTelefone))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLaPesquisa)
                    .addComponent(jTePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuPesquisarActionPerformed
        //jTaResultado.set(new SemEspeciais());
        jTaResultado.setModel(new DefaultTableModel());//SEMPRE QUE CLICO NO BOTAO PESQUISAR ZERO A TABELA
        
        comp = jTePesquisa.getText();
        
        Object Colunas[] = {"Os", "Nome", "Telefone", "Tipo", "Marca", "Modelo" }; // objeto com as colunas da tabela
        Modelo = new DefaultTableModel(Colunas, 0); //setando a tabela de modo default
        jTaResultado.setRowSorter(new TableRowSorter(Modelo));
                   
        if(jRaNome.isSelected()){
            for(int i =0; i < palavras.length; i++){
                System.out.println(comp);
                //if(palavras[i].substring(149, 169).contains(comp.toUpperCase())){ //149, 169 por nome 
                if(palavras[i].substring(0, 4).contains("0~")||palavras[i].substring(0, 4).isEmpty()
                    || palavras[i].substring(0, 4).equals("   ")){ 
                    
                    //Modelo.removeRow(i);//remove a linha;
                }else{
                    Object linhaa[]; 
                    
                        if(palavras[i].substring(149, 169).contains(comp.toUpperCase())){ //149, 169 por nome
                        linhaa = new Object[]{palavras[i].substring(0, 4),
                        palavras[i].substring(149, 169), palavras[i].substring(169, 189),
                        palavras[i].substring(12, 25), palavras[i].substring(32, 41),palavras[i].substring(25, 32)};
                        
                        Modelo.addRow(linhaa);//adiciona a linha
                        //Modelo.removeRow(i);//remove a linha
                        
                             
                     
                           
                    jTaResultado.setModel(Modelo); //a tabela recebe o modelo
                 
                }
                }
                
            } 
                        
            if(jTaResultado.getRowCount()== 0){ //caso não retorne nada na pesquisa nome
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
            }
                        
        }else{
            for(int i =0; i < palavras.length; i++){
                if(palavras[i].substring(169, 189).contains(comp.toUpperCase())){ // 169,189 por telefone
                    //System.out.println(linha.toUpperCase().contains(comp.toUpperCase()));;;
                    //comp = linha.trim(); // trim tira os espaços que antecedem e que ficam depois
                    Object linhaa[] = new Object[]{palavras[i].substring(0, 4),
                    palavras[i].substring(149, 169), palavras[i].substring(169, 189),
                    palavras[i].substring(12, 25), palavras[i].substring(32, 41),palavras[i].substring(25, 32)};
                    // as , após fechamento de cada parenteses separa uma coluna da outra no obj
                                
                    Modelo.addRow(linhaa);//adiciona a linha 
                           
                    jTaResultado.setModel(Modelo); //a tabela recebe o modelo
                    
                }else{
                    
                }
            }
            //jTaResultado.setEnabled(false);
            if(jTaResultado.getRowCount()== 0){ //caso não retorne nada na pesquisa numero
                JOptionPane.showMessageDialog(null, "Numero de telefone não encontrado!");
            }   
            jTaResultado.setEnabled(false);
        }

    }//GEN-LAST:event_jBuPesquisarActionPerformed

    private void jRaNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRaNomeMouseClicked
        if(jRaNome.isSelected()){
        jTePesquisa.setEnabled(true);
        jTePesquisa.setDocument(new SemEspeciais());
        }
    }//GEN-LAST:event_jRaNomeMouseClicked

    private void jRaTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRaTelefoneMouseClicked
        jTePesquisa.setEnabled(true);
        jTePesquisa.setDocument(new SoNumeros());
    }//GEN-LAST:event_jRaTelefoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupNomeTel;
    private javax.swing.JButton jBuPesquisar;
    private javax.swing.JLabel jLaPesquisa;
    private javax.swing.JRadioButton jRaNome;
    private javax.swing.JRadioButton jRaTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTaResultado;
    private javax.swing.JTextField jTePesquisa;
    // End of variables declaration//GEN-END:variables
}
